name: kev
favicon: null
layout_spectrum: 0.18942
typography_spectrum: 0.55045
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2b3b30'
    - '#5e6d5a'
    - '#a8a9a4'
    - '#cdcac0'
  brandStrength: 0.5625
  lightness: 0.625
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
