name: kev
favicon: null
layout_spectrum: 0.473172162193805
typography_spectrum: 0.15813753777183592
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5835219696164131
  lightness: 0.5470345290377736
  saturation: 0.9978089367505163
  rhythmicContrast: 0.0018825437873601913
purpose: []
